# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55c1c0bdc64c3a19f8429fcb2b10c1d437525828f7fd99cf26c6467683214c112c6ee36782415faebc65c063afe61e43ec3ae97f6f10bef04b4f3cdb31e8ba01

test:
  secret_key_base: 3862678041b0cfb82921f7e1a7a61c2ed2ff69a952e343a2904d33567a6f961827fbb45e3b0cdac1690577b585f3cc1a7ae7728c657cf12831169cdc82c84429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
